package config

import (
	"os"
	"testing"
	"time"

	"sigs.k8s.io/yaml"
)

// crdPath is the generated CRD the chart installs, regenerated by hack/gen-crd.sh.
// A literal rather than a filepath.Join, so it reads as the fixed path it is.
const crdPath = "../../charts/k2a-token-sync-crds/files/k2a-token-sync.io_clusterconnections.yaml"

// Every default lives in two places: a kubebuilder marker, which the API server
// applies at admission, and a Go constant, which covers the paths that run before
// any object exists — bootstrap, and any field the schema leaves empty. Drift
// between them would be close to invisible: a cluster would be prepared with one
// lifetime and renewed with another, and nothing would report a disagreement.
func TestSchemaDefaultsMatchTheGoDefaults(t *testing.T) {
	t.Parallel()

	spec := crdSpecProperties(t)

	for _, tc := range []struct {
		field string
		want  time.Duration
	}{
		{"tokenTTL", defaultTokenTTL},
		{"selfTokenTTL", defaultSelfTokenTTL},
		{"expiryWarnThreshold", defaultExpiryWarnThreshold},
	} {
		raw, ok := stringDefault(spec, tc.field)
		if !ok {
			t.Errorf("%s has no default in the schema, so an omitted value would reach the code as empty", tc.field)
			continue
		}
		got, err := time.ParseDuration(raw)
		if err != nil {
			t.Errorf("the schema default for %s (%q) is not a duration: %v", tc.field, raw, err)
			continue
		}
		if got != tc.want {
			t.Errorf("%s: schema defaults to %s, the code to %s", tc.field, got, tc.want)
		}
	}

	for _, tc := range []struct {
		field string
		want  string
	}{
		{"selfServiceAccountName", defaultSelfServiceAccount},
		{"secretName", ""}, // derived from the cluster name, so deliberately not defaulted
	} {
		got, ok := stringDefault(spec, tc.field)
		if tc.want == "" {
			if ok {
				t.Errorf("%s has a schema default (%q), which would be written into every object", tc.field, got)
			}
			continue
		}
		if !ok {
			t.Errorf("%s has no default in the schema", tc.field)
			continue
		}
		if got != tc.want {
			t.Errorf("%s: schema defaults to %q, the code to %q", tc.field, got, tc.want)
		}
	}

	sa, ok := spec["serviceAccount"].(map[string]any)
	if !ok {
		t.Fatal("the schema has no serviceAccount property")
	}
	def, ok := sa["default"].(map[string]any)
	if !ok {
		t.Fatal("serviceAccount has no default, so an object omitting it would name no identity")
	}
	if def["name"] != defaultServiceAccountName {
		t.Errorf("serviceAccount.name: schema defaults to %v, the code to %q", def["name"], defaultServiceAccountName)
	}
	if def["namespace"] != defaultServiceAccountNS {
		t.Errorf("serviceAccount.namespace: schema defaults to %v, the code to %q",
			def["namespace"], defaultServiceAccountNS)
	}
}

func crdSpecProperties(t *testing.T) map[string]any {
	t.Helper()

	raw, err := os.ReadFile(crdPath)
	if err != nil {
		t.Fatalf("reading the generated CRD: %v", err)
	}

	var crd struct {
		Spec struct {
			Versions []struct {
				Name   string `json:"name"`
				Schema struct {
					OpenAPIV3Schema struct {
						Properties struct {
							Spec struct {
								Properties map[string]any `json:"properties"`
							} `json:"spec"`
						} `json:"properties"`
					} `json:"openAPIV3Schema"`
				} `json:"schema"`
			} `json:"versions"`
		} `json:"spec"`
	}
	if err := yaml.Unmarshal(raw, &crd); err != nil {
		t.Fatalf("parsing the generated CRD: %v", err)
	}
	if len(crd.Spec.Versions) != 1 {
		t.Fatalf("the CRD serves %d versions; this test assumes one", len(crd.Spec.Versions))
	}

	props := crd.Spec.Versions[0].Schema.OpenAPIV3Schema.Properties.Spec.Properties
	if len(props) == 0 {
		t.Fatal("the CRD's spec schema has no properties, so this test would assert nothing")
	}
	return props
}

func stringDefault(props map[string]any, field string) (string, bool) {
	prop, ok := props[field].(map[string]any)
	if !ok {
		return "", false
	}
	value, ok := prop["default"].(string)
	return value, ok
}
