// Package legal exposes legal notices embedded in every binary.
package legal

import _ "embed"

// thirdPartyNotices is generated by hack/gen-notices.sh.
//
//go:embed THIRD_PARTY_NOTICES
var thirdPartyNotices string

// ThirdPartyNotices returns the dependency licenses and attribution notices
// embedded at build time.
func ThirdPartyNotices() string {
	return thirdPartyNotices
}
